### ISSUE TITLE
Add Documentation for build.fsproj pattern

### ISSUE THREAD

**Issue by aboy021** [fsprojects/FAKE#2695]
### Description

I've recently moved from using the FAKE script runner to having a stand alone **build.fsproj** project that uses FAKE libraries. It's an approach that others have been using, and I've found it to be excellent so far. It would be great if there were some documentation on the [Project Home Page](https://fake.build/) on how to do this.

The following projects both use the **build.fsproj** approach, albeit somewhat differently:

- [TheAngryByrd/MiniScaffold: F# Template for creating and publishing libraries targeting .NET 6.0 `net6.0` or console apps .NET 6.0 `net6.0`.](https://github.com/TheAngryByrd/MiniScaffold)
- [CompositionalIT/SAFE-Dojo: An introductory dojo to learn how to develop full stack web applications in F#](https://github.com/CompositionalIT/SAFE-Dojo)

There was some mention of this approach in issue #2627, and it is a good work around.

There's an question on Stack Overflow ([visual studio code - Fix for "Package manager key paket was not registered" in build.fsx](https://stackoverflow.com/questions/66665009/fix-for-package-manager-key-paket-was-not-registered-in-build-fsx/73283729)) where the maintainer for Ionide suggested a few solutions including using a "build project".

[I wrote an answer to the StackOverflow question](https://stackoverflow.com/a/73283729/198452) sharing some basic steps on how to use the **build.fsproj** approach.

I'd really like to see this approach become a first class option as it gives a great debugging experience, even in Visual Studio, and seems to have better tooling support. 

---

### Repro steps

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Known workarounds

N/A

### Related information 

N/A

**Comment by yazeedobaid** [comment]
Thanks a lot for suggesting the solution. Yes, absolutely we can add this approach to the different ways that FAKE can be used. I like the structure of your answer in StackOverflow. Would you like to send a PR with it?

By the way, we are currently experimenting with the solution of using `dotnet fsi` directly instead of the FAKE runner. Since now FSI supports resolving dependencies from the script, even with Paket by adding it to the dependency managers list on the machine. However, this has the drawback of caching and speed of running the script. So FAKE runner compiles the script on the first run and for subsequent runs, it uses the compiled assembly, hence the compilation phase is skipped.

**Comment by yazeedobaid** [comment]
I added the build project installation approach in the documentation, [Run FAKE using a dedicated build project](https://fake.build/guide/getting-started.html#Run-FAKE-using-a-dedicated-build-project). Please feel free to update it if I'm missing something. Thanks!
