### ISSUE TITLE
Update to .NET 7

### ISSUE THREAD

**Issue by OnurGumus** [fsprojects/FAKE#2713]
### Description

Title says all.

**Comment by OnurGumus** [comment]
@yazeedobaid , while it works against .NET 7, it still requires .NET 6 SDK to exist

https://github.com/fsprojects/FAKE/blob/ada1877316c83eebb6c3695dd8e234c906276a0d/src/app/Fake.Runtime/SdkAssemblyResolver.fs#L203

So I don't think this problem is fixed.

**Comment by yazeedobaid** [comment]
@OnurGumus we are not planning to support .NET 7 in the runner. Currently, it is using .NET 6 since it is the current LTS release. Before this, we supported .NET 6 and NETSTANDARD reference assemblies and we had a lot of issues that we needed to do a workaround to fix them, which led us to drop support for NETSTANDARD in FAKE v6.

If you would like to use .NET 7 reference assemblies for any reason, you can check the alternative ways to use FAKE beside runner in [Different ways to run FAKE](https://fake.build/guide/getting-started.html#Different-ways-to-run-FAKE). An increasingly popular approach to using FAKE is to [Run FAKE using a dedicated build project](https://fake.build/guide/getting-started.html#Run-FAKE-using-a-dedicated-build-project).

**Comment by OnurGumus** [comment]
I understand but, In either case, doesn't this necessitate both .NET 6 and .NET 7 SDK's to exist in CI/CD or build images? 
This doesn't sound ideal.

**Comment by yazeedobaid** [comment]
No, other approaches utilize .NET and FSI, so it will use the currently installed .NET SDK you have. The other two approaches use .NET and FSI to resolve the dependencies in the script file, instead of the FAKE runner. Which will parse the Paket section, determine the dependencies, and add the .NET SDK reference assemblies.

**Comment by OnurGumus** [comment]
Hello @yazeedobaid  when I tried the last approach I end up with 
Unhandled exception. System.Exception: Cannot retrieve 'Fake.Core.Target.ArgResults' as we have no fake context
Any ideas?

**Comment by OnurGumus** [comment]
Second way also won't work 
failing with /.fake/build.fsx/intellisense_lazy.fsx'  doesn't exist and it doesn't/

**Comment by yazeedobaid** [comment]
@OnurGumus for the last approach, you need to create a FAKE execution context in the build script. Like this:
```f#
Context.FakeExecutionContext.Create false "build.fsx" []
|> Context.RuntimeContext.Fake
|> Context.setExecutionContext
```

You can check samples in the docs for that method. For example, in MiniScaffold, [these lines](https://github.com/TheAngryByrd/MiniScaffold/blob/c77b76bfba47b74e10774a7c3be61c6aa395d4f5/build/build.fs#L545-L550)

For the second way you also don't need the lazy file, it was for runner and that method doesn't use it, so u can remove that statement.

**Comment by Thorium** [comment]
Same still here: Could not find a suitable .NET 6 runtime version matching SDK version: 8.0.205

**Comment by OnurGumus** [comment]
@Thorium you can use the second way. That works fine by me. .fsx scripts won't work

**Comment by Thorium** [comment]
Latest Fake 6.1.1 should have this fixed.
